### ISSUE TITLE
Going past the end of the program causes a crash

### ISSUE THREAD

**Issue by morganthomas** [Orbis-Tertius/coq-tinyram#11]
Steps to reproduce:

1. Add the following data to a text file (load-before-store.bin):
11011000000000001111111111111110
2. Run:
```
coq-tinyram load-before-store.bin /dev/null /dev/null 6
```

Expected result: The program did not halt in the specified number of steps.

Actual result: The programs halts with answer 1.

Explanation: this program consists of one instruction, which loads from the last word-aligned memory address.

**Comment by morganthomas** [comment]
Or maybe the issue here is that the address is unaligned?

**Comment by morganthomas** [comment]
It appears that the root cause of the issue is that the program answers 1 when the program counter goes past the end of the program, but the expectation is for it to read the zero instruction (which happens to be a no-op) when the program counter goes past the end.

**Comment by AHartNtkn** [comment]
On page 5 of the TinyRAM 2.000 spec, the last sentence of the paragraph starting with "Harvard architecture" reads;

> If pc is not an integer in {0, . . . , L − 1}, where L is the number of instructions in P, then the instruction answer 1 is fetched as default.

This seems like the intended behavior, according to the spec.

**Comment by morganthomas** [comment]
Oh, okay. Then this is a non-issue. It needs to be fixed on the other side.
